# Generated by Django 2.2 on 2021-02-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieview',
            name='media_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
