# Generated by Django 2.2 on 2021-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('overview', models.CharField(max_length=512)),
                ('popularity', models.CharField(max_length=128)),
                ('poster', models.CharField(max_length=128)),
                ('release_date', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
            ],
        ),
    ]
